version: '3.2'
services:
    oracle:
     image: sath89/oracle-12c
     expose:
      - "8080"
      - "1521"
      - "6800"
     environment:
      - MANUAL_DBCA=true
      - VNC_PASSWORD=password
      - IMPORT_FROM_VOLUME=${IMPORT_FROM_VOLUME}
     volumes:
      - /mnt/data0/oracle:/u01/app/oracle:rw
    mongodb:
     image: library/mongo
     expose:
      - "27017"
     volumes:
      - /mnt/data0/mongo:/data/db:rw
      - /tmp:/tmp:rw
    kafka:
     image: softsky/kafka
     expose:
      - "2181"
      - "9092"
    kafka-connect:
     image: softsky/kafka-connect
#    eclipse:
#     image: psharkey/eclipse
#     links:
#      - oracle
#      - mongodb
#     volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix
#      - ${HOME}/.m2:/root/.m2
#      - ${HOME}/dev:/root/workspace
#     environment:
#      - DISPLAY=:0.0
        
